# -*- coding: utf-8 -*-
"""integrity_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHKdTrdnWge0fogdw-hSNyT1Kqsgqfe4
"""

# Install reportlab for PDF generation
!pip install reportlab

import os
import hashlib
import json
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

# ==============================
# CONFIGURATION
# ==============================
# Directory to monitor (change if needed)
MONITOR_DIR = "."

# File where hashes will be stored
HASH_FILE = "file_hashes.json"
REPORT_PDF_FILE = "file_integrity_report.pdf"

# ==============================
# UTILITY FUNCTION: Generate PDF
# ==============================
def generate_pdf(title, content_lines, filename):
    """
    Generates a PDF report from a list of content strings.
    """
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(f"<b>{title}</b>", styles['Title']))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 12))

    for line in content_lines:
        elements.append(Paragraph(str(line), styles['Normal']))
        elements.append(Spacer(1, 6))

    doc.build(elements)
    print(f"✅ PDF report saved: {filename}")

# ==============================
# FUNCTION: Calculate File Hash
# ==============================
def calculate_hash(file_path):
    """
    Calculates SHA-256 hash of a file.
    Reads file in chunks for efficiency.
    """
    sha256 = hashlib.sha256()

    try:
        with open(file_path, "rb") as f:
            while chunk := f.read(4096):
                sha256.update(chunk)
        return sha256.hexdigest()
    except Exception as e:
        # print(f"Error reading {file_path}: {e}") # Commented to reduce console clutter
        return None


# ==============================
# FUNCTION: Scan Directory
# ==============================
def scan_files(directory):
    """
    Scans all files in directory and returns a dictionary
    of file paths and their hashes.
    """
    file_hashes = {}

    for root, dirs, files in os.walk(directory):
        for file in files:
            file_path = os.path.join(root, file)

            # Skip the hash file itself and the PDF report file
            if file_path.endswith(HASH_FILE) or file_path.endswith(REPORT_PDF_FILE):
                continue

            file_hash = calculate_hash(file_path)
            if file_hash:
                file_hashes[file_path] = file_hash

    return file_hashes


# ==============================
# FUNCTION: Load Previous Hashes
# ==============================
def load_previous_hashes():
    """
    Loads stored hashes from JSON file.
    """
    if not os.path.exists(HASH_FILE):
        return {}

    try:
        with open(HASH_FILE, "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading previous hashes: {e}")
        return {}


# ==============================
# FUNCTION: Save Hashes
# # ==============================
def save_hashes(hashes):
    """
    Saves hashes to JSON file.
    """
    try:
        with open(HASH_FILE, "w") as f:
            json.dump(hashes, f, indent=4)
    except Exception as e:
        print(f"Error saving hashes: {e}")


# ==============================
# FUNCTION: Compare Hashes
# ==============================
def compare_hashes(old_hashes, new_hashes):
    """
    Compares old and new hashes and returns a list of report lines.
    """
    report_lines = []
    changed_detected = False

    # Check for modified or unchanged files
    for file, new_hash in new_hashes.items():
        old_hash = old_hashes.get(file)

        if old_hash:
            if old_hash == new_hash:
                report_lines.append(f"[OK] Unchanged: {file} | Hash: {new_hash}")
            else:
                report_lines.append(f"[MODIFIED] {file} | Old Hash: {old_hash} | New Hash: {new_hash}")
                changed_detected = True
        else:
            report_lines.append(f"[NEW] {file} | Hash: {new_hash}")
            changed_detected = True

    # Check for deleted files
    for file in old_hashes:
        if file not in new_hashes:
            report_lines.append(f"[DELETED] {file} | Last Known Hash: {old_hashes[file]}")
            changed_detected = True

    if not changed_detected:
        report_lines.append("\n✔ All files are intact. No changes detected.")
    else:
        report_lines.append("\n⚠ Changes detected in monitored files.")

    return report_lines


# ==============================
# MAIN PROGRAM
# ==============================
def main():
    print("Scanning files...")

    current_hashes = scan_files(MONITOR_DIR)
    previous_hashes = load_previous_hashes()

    if not previous_hashes:
        print("\nNo previous record found. Creating baseline...")
        save_hashes(current_hashes)
        print("Baseline created successfully.")
        report_lines = ["Baseline created. No changes to report yet."]
    else:
        report_lines = compare_hashes(previous_hashes, current_hashes)
        save_hashes(current_hashes)

    # Print report to console
    print("\n=== File Integrity Report ===\n")
    for line in report_lines:
        print(line)

    # Generate PDF report
    generate_pdf("File Integrity Report", report_lines, REPORT_PDF_FILE)


if __name__ == "__main__":
    main()

# The code from this cell is being consolidated into a single file below. This cell can now be safely removed.

